JRELEASER_GITHUB_TOKEN="EMPTY"
JRELEASER_GPG_PASSPHRASE="supersecretpassword"
JRELEASER_MAVENCENTRAL_TOKEN="OKweLR2RHxHAZCwGhuAXerzsZxSIYpMNdJpZOuAYzaFs"
JRELEASER_MAVENCENTRAL_USERNAME="e+zDRuHF"
JRELEASER_GPG_PUBLIC_KEY="""-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEaELh0hYJKwYBBAHaRw8BAQdA/fxShzseDWMhhcVy/DMUlLvTLfDM9/2aqjT/
rpGsnR20IElseWEgUG9wb3YgPGlicG9wb3Y4N0BnbWFpbC5jb20+iJYEExYKAD4W
IQRhdDI25zt0eNmPA3EBsF/TIsS6hwUCaELh0gIbAwUJBaOagAULCQgHAgYVCgkI
CwIEFgIDAQIeAQIXgAAKCRABsF/TIsS6h+5aAQC6/xwrYU10mIctb4O1FbdhE2qm
jooPEoE0J79QSz+90wD9E7HSbQYVQF+khW5R9o9vat0BoyUEQ2GEnlPxmCEAJQK4
OARoQuHSEgorBgEEAZdVAQUBAQdAX+zYYyHIOBEzfVsysNLkOQAXGKPW6OBcH6lt
/mjt+xwDAQgHiH4EGBYKACYWIQRhdDI25zt0eNmPA3EBsF/TIsS6hwUCaELh0gIb
DAUJBaOagAAKCRABsF/TIsS6h1h3AP4qQ6jEPCLVTdLasGf6P7dSBQ1eoa+uhVuv
9BDMkfPq6gD+KpZ8RQat65rGgZ55AtP3sHeYXZJGkOXZIqHwha71UA0=
=LEnU
-----END PGP PUBLIC KEY BLOCK-----"""
JRELEASER_GPG_SECRET_KEY="""-----BEGIN PGP PRIVATE KEY BLOCK-----

lIYEaELh0hYJKwYBBAHaRw8BAQdA/fxShzseDWMhhcVy/DMUlLvTLfDM9/2aqjT/
rpGsnR3+BwMC1VAoYz8SGQL5VlUKupf/H+Ksom/px7vgAfHEeg27v00o5ESosk1X
pCilKCi0FTYhDmhjsj9MykUn4pCxmdO8MTshtiwM5+mAJ9w5meE4ebQgSWx5YSBQ
b3BvdiA8aWJwb3Bvdjg3QGdtYWlsLmNvbT6IlgQTFgoAPhYhBGF0MjbnO3R42Y8D
cQGwX9MixLqHBQJoQuHSAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
AAoJEAGwX9MixLqH7loBALr/HCthTXSYhy1vg7UVt2ETaqaOig8SgTQnv1BLP73T
AP0TsdJtBhVAX6SFblH2j29q3QGjJQRDYYSeU/GYIQAlApyLBGhC4dISCisGAQQB
l1UBBQEBB0Bf7NhjIcg4ETN9WzKw0uQ5ABcYo9bo4FwfqW3+aO37HAMBCAf+BwMC
R9DVqOI5i4/5m9NJYldcBafJHrP26VECag2bBhm++1kHbXWrtHbw8fpJyBXSsTYr
ETH9anM/uXwe/X/h1n00DUB9rGjDzOkD7WzN9W8Broh+BBgWCgAmFiEEYXQyNuc7
dHjZjwNxAbBf0yLEuocFAmhC4dICGwwFCQWjmoAACgkQAbBf0yLEuodYdwD+KkOo
xDwi1U3S2rBn+j+3UgUNXqGvroVbr/QQzJHz6uoA/iqWfEUGreuaxoGeeQLT97B3
mF2SRpDl2SKh8IWu9VAN
=rHYl
-----END PGP PRIVATE KEY BLOCK-----"""