[versions]
agp = "8.9.2"
kotlin = "2.1.0"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.10.1"
composeBom = "2025.10.01"
jetbrainsKotlinJvm = "1.9.0"
symbolProcessingApi = "2.1.0-1.0.29"
viewmodelAndroid = "2.9.4"
jreleaser = "1.14.0"
fragmentKtx = "1.8.9"
navigation = "2.9.5"
junit = "4.13.2"
kotlinpoet = "1.18.1"
mockito = "5.14.2"
kctfork = "0.7.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
symbol-processing = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }
symbol-processing-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "symbolProcessingApi" }
androidx-viewmodel-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose-android", version.ref = "viewmodelAndroid" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kctfork-core = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kctfork" }
kctfork-ksp = { group = "dev.zacsweers.kctfork", name = "ksp", version.ref = "kctfork" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kspAndroid = { id = "com.google.devtools.ksp", version.ref = "symbolProcessingApi" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

